#!/bin/sh
unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4 LUA_CPATH LUA_CPATH_5_2 LUA_CPATH_5_3 LUA_CPATH_5_4
LUAROCKS_SYSCONFDIR="/home/kryuchkov/git/ngx_waf_ingress_controller/src/luajit/etc/luarocks" LUA_PATH="/home/kryuchkov/git/ngx_waf_ingress_controller/src/luarocks-3.8.0/src/?.lua;;" exec "/home/kryuchkov/git/ngx_waf_ingress_controller/src/luajit/bin/luajit" "/home/kryuchkov/git/ngx_waf_ingress_controller/src/luarocks-3.8.0/src/bin/luarocks-admin" --project-tree="/home/kryuchkov/git/ngx_waf_ingress_controller/src/luarocks-3.8.0/lua_modules" "$@"
