name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tag pushes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Install Docker in the runner directly instead of using Docker-in-Docker
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    # Build the Ingress Controller binaries
    - name: Run build script
      run: |
        bash scripts/build_with_controller_ssl3.sh

    # Build and tag the Docker image
    - name: Build Docker image
      run: |
        docker buildx build -f Dockerfile --tag ghcr.io/cloudrhinoltd/nginx-ingress:${{ github.ref_name }} .

    # Optional: Test the Docker image before pushing
    - name: Test Docker image
      run: |
        docker run --rm ghcr.io/cloudrhinoltd/nginx-ingress:${{ github.ref_name }} nginx -t

    - name: Push Docker image
      run: |
        docker push ghcr.io/cloudrhinoltd/nginx-ingress:${{ github.ref_name }}
