name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tag pushes
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  id-token: write # Required for Cosign signing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ghcr.io/cloudrhinoltd/nginx-ingress

      # Build and test Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5.0.0
        id: build-and-push
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: Test the Docker image before pushing
      - name: Test Docker image
        run: |
          docker run --rm ghcr.io/cloudrhinoltd/nginx-ingress:${{ steps.meta.outputs.tags }} nginx -t

      # Push the Docker image
      - name: Push Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ghcr.io/cloudrhinoltd/nginx-ingress:${{ steps.meta.outputs.tags }}

      # Sign the published Docker image
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
