name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tag pushes
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
       fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Cache dependencies to speed up the build process
    - name: Cache LuaRocks dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/luarocks
        key: ${{ runner.os }}-luarocks-${{ hashFiles('**/lua_rocks') }}
        restore-keys: |
          ${{ runner.os }}-luarocks-

    - name: Get latest tag
      id: get_tag
      run: |
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "LATEST_TAG=${latest_tag}" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        bash scripts/build_with_controller_ssl3.sh
        docker buildx build -f Dockerfile --tag ghcr.io/cloudrhinoltd/nginx-ingress:${{ env.LATEST_TAG }} --load .

    # Optional: Test the Docker image before pushing
    - name: Test Docker image
      run: |
        docker run --rm ghcr.io/cloudrhinoltd/nginx-ingress:${{ env.LATEST_TAG }} nginx -t

    - name: Push Docker image
      run: |
        docker push ghcr.io/cloudrhinoltd/nginx-ingress:${{ env.LATEST_TAG }}
